# -*- coding: utf-8 -*-
# Part of Odoo. See LICENSE file for full copyright and licensing details.
{
    'name': 'Cabinet medical',
    'version': '1.1',
    'Company': 'Multi Canal Services',
    'author': "Multi canal services, Team odoo",

    'category': 'Health center',
    'summary': 'patients, dentitions',
    'description': """ Ce module va permettre de gérer les processus métiers d'un cabinet dentaire""",
    'depends': ['base', 'mail', 'account', 'account_accountant', 'resource', 'hr', 'base_setup', 'web_kanban',
                'report'],
    'data': [
        'views/patient_view.xml',
        'views/traitment_view.xml',
        'views/hr_view.xml',
        'views/certificat_medical.xml',
        'views/ord_medical.xml',
        'report/exam_report.xml',
        'report/devis_report.xml',
        'report/devis_assureur.xml',
        'report/expertise_report.xml',
        'report/report_invoice_document.xml',
        'report/report_invoice_document_assurance.xml',
        'report/certificat_medical_report.xml',
        'report/ord_medical.xml',
        'report/account_invoice_custom.xml',
        'report/ord_medical.xml',
        'report/patient.xml',
        'report/consultation_report.xml',
        'report/record.dents.csv',
        'views/apointment.xml',
        'views/expertise.xml',
        'views/examen.xml',
        'views/soins.xml',
        'views/menu.xml',
        'views/assurance.xml',
        'views/consultation.xml',
        'views/document_view.xml',
        'views/type_document.xml',
        'views/templates.xml',
        'views/medicament.xml',
        'views/templates_mail.xml',
        'security/dental_security.xml',
        'views/base_config_view.xml',
        'security/ir.model.access.csv',

    ],
    'demo': [],
    'installable': True,
    'application': True,
    'auto_install': False,
}
